export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const KITTIES_REQUEST = 'KITTIES_REQUEST';
export const KITTIES_SUCCESS = 'KITTIES_SUCCESS';
export const KITTIES_FAILED = 'KITTIES_FAILED';
